---
title: "Introduction"
author: "Victor maj Møk 1"
date: "2024-12-16"
output:
  pdf_document: default
  html_document: default
---


#Introduction
Compulsory Licensing of Patents and Innovation looks at the intervention TWEA has had on  patents in organic chemistry to US firms. The Trading with the Enemy Act (TWEA) of 1917   permitted  US  firms  to  violate  enemy-owned  patents  if  they  contributed  to  the  war  effort.
in this report we are trying to look at the causal effect the intervention of TWEA has had on US Domestic patenting. 
the report therefore tries to answear the main research question. 
"Does compulsory licensing increase or discourage domestic invention in countries that license foreign technologies?"

In order to help us answer this research question is the dataframe "exam_TWEA.r" provited. which is the same dataset as our main reference "Moser, P., Voena, A. (2012).  Compulsory licensing:  Evidence from the tradingwith the enemy act.American Economic Review, 102(1), 396-427" used in their study and will be the main papier we are refereeing to thought the report. the data provided is panel data. this is because the data looks at the following  variables relevant for the report:
\vspace{1cm}
```{r, echo = FALSE}
library(kableExtra)
var_desc <- data.frame(
  Variable = c("uspto_class", "grntyr", "count_cl", "anypatent", "count_usa", 
               "counter_cl_itt", "mainclass_id", "subcl", "twea"),
  Description = c(
    "specific technology grouping of patent based on common subject matter",
    "year of patent grant",
    "Number of patents adopted under forced licensing",
    "1 if any patent have been adopted under forced licensing.",
    "Number of patents developed domestically",
    "Number of available patents under forced licensing",
    "Main class code",
    "Subclass code",
    "Whether TWEA was enacted"
  )
)

kable(var_desc, format = "latex", booktabs = TRUE, 
      caption = "Variable Descriptions") %>%
  kable_styling(latex_options = c("striped", "hold_position"))
```

\vspace*{\fill}

so each observation point provides in the dataframe is the evolution of patents throughout the years. for intance if we look at the fir st observation of the dataframe we find the organic chemistry patent 008/09410D. which we start measuring at year 1875. we this patent evolution of the patent until year 1939 and then switch to observe a new patent. this is why the data provied is panel data as we observations are for the same subjects each time.
moreover since the data proved are longitudinal studies this tells us that the data is observational rather than experimental. this is further verified since we are 





