---
title: "IV"
author: "Victor maj Møk 1"
date: "2024-12-13"
output: html_document
---

Consider the following DAG for a problem when using Instrumental Variables. Indsæt DAG
Consider also the corsponding SWIG. 

In order to succesfully introduces a Instrumental Variables to establish a casusal relation. we must make sure that the Instrumental Variables satisfies. the exclusion restriction, we futher have to make sure that there is a non-zero first-stage and lastly that the monotonicity assumption holdes. if we are looking at local average treatment effect (LATE).

the research paper Enemy patents as a Instrumental Variables where it goes through the mediator number of license to the outcome patents by us inventors. the papir says 

"Enemy  patents  is  highly  correlated  with  the  number  of  licenses  that  were  granted  to  US  firms,  but  variation  in  enemy  patents(other  than  those  that  were  licensed) should not by itself increase domestic invention"
here they are reffering to the "exclusion restriction" and the "non-zero first-stage" assumption of Instrumental Variables. 

The exclusion restriction:
 however the paprr does not show that these assumption hold. the no exclusion restriction is an untestable assumption, so we need to logically argue that there is a no path from 
z -> y other that only through the mediator. 

skriv om hvorfor at at det holder. 


non-zero first-stage:
not lets check to see if we have a strong instrument. the non-zero first-stage assumption is a testable assumption. so using a standard Technics used in the turtoriels we find that.
not that in the papir is looking at the postTWEA in the IV part. 

 
 